### ISSUE TITLE
Site not working properly

### ISSUE THREAD

**Issue by geetanshu-m** [joomla-projects/gsoc18_adaptive_images#2]
### Steps to reproduce the issue

After this commit(https://github.com/joomla-projects/gsoc18_adaptive_images/compare/69eaf4ed10...6544913b63) site starts showing following errors...
![screenshot 193](https://user-images.githubusercontent.com/18314265/40165689-4537cfea-59da-11e8-9683-e08d11e1ddd3.png)
![screenshot 195](https://user-images.githubusercontent.com/18314265/40165697-4987ebe8-59da-11e8-872e-f884b3a2af79.png)
![screenshot 194](https://user-images.githubusercontent.com/18314265/40165702-4b4a547a-59da-11e8-9c1d-954023dc99f3.png)

**Comment by geetanshu-m** [comment]
@zero-24 please help me out...

**Comment by zero-24** [comment]
Hmm this seams to be a upstream issue. Can you please report that including a stacktrace (just enable debug) to the main repo? Please tag than `@laoneo` and `@wilsonge` as this seams to be something with the new toolbar in the mm :)

**Comment by zero-24** [comment]
This is what i mean by main repo :P https://github.com/joomla/joomla-cms/issues/new?template=Bug_report.md
